### PR TITLE
Add tests for metadata and fix anything that is obviously wrong

### LINKED ISSUE #98: Metadata isn't using the blog post title
This is something that we noticed on the work to convert the Ember Blog to empress-blog: https://github.com/ember-learn/ember-blog/pull/7

it's pretty simple: the metadata isn't right

### PR DESCRIPTION
**Pull request by mansona**
This is mostly a first-pass on fixing metadata and adding some regression tests so that we can know if things break in the future 👍 we can probably do a better job on a lot of stuff but for now this is already a lot better than we had 🎉 

If the diff is a bit big to review all at once, I separated the commits to be very specific so you can review commit by commit if it helps 👍 

Fixes #98

### CODE REVIEW

**Review by nickschot — APPROVED** [review]

File: addon/helpers/excerpt.js [hunk 1]
```diff
@@ -6,11 +6,7 @@ import downsize from 'downsize-cjs';
 export function getExcerpt(html, truncateOptions) {
   truncateOptions = truncateOptions || {};
   // Strip inline and bottom footnotes
-  var excerpt = html.replace(/<a href="#fn.*?rel="footnote">.*?<\/a>/gi, '');
-  excerpt = excerpt.replace(/<div class="footnotes"><ol>.*?<\/ol><\/div>/, '');
-  // Strip other html
-  excerpt = excerpt.replace(/<\/?[^>]+>/gi, '');
-  excerpt = excerpt.replace(/(\r\n|\n|\r)+/gm, ' ');
+  var excerpt = stripHTML(html);
```
Comment (nickschot) [inline addon/helpers/excerpt.js:9]: hmmmmmm var

Comment (mansona) [reply addon/helpers/excerpt.js]: omg 🙈  I am pretty sure this came from a copy pasta. fixed now tho!
